### ISSUE TITLE
Placeholder on tab broken

### ISSUE THREAD

**Issue by Faustyu1** [digitaldrugstech/prdx-bugtracker#11]
### Опишите баг

Сломали плейсхолдер

### Шаги для воспроизведения поведения

зайдите на креатив и в табе сломался плейсхолдер тпс. Скорее всего вы поменяли ядро а спарк не поставили

### Ожидаемое поведение

Должен быть тпс

### Технические характеристики

- ОС: Windows / Mac / Linux
- Видеокарта, процессор
- Оперативная память

### Minecraft (если ошибка связана с визуальными багами / сложностями при входе на сервер)

- Версия: [1.20.6 Fabric]
- Лаунчер [Prism Launcher]

**Comment by itsSourCream** [comment]
Миниплейсхолдеры слетели. Спарк в последних версиях встроен в paper btw

**Comment by itsSourCream** [comment]
Fixed
