### ISSUE TITLE
Авторизация должна работать по айпи клиента майнкрафта, а не браузера

### ISSUE THREAD

**Issue by vrtkk** [digitaldrugstech/prdx-bugtracker#14]
### Опишите проблему

Авторизация сохраняет как trustworthy айпи с которого вызвали prdx.so/api/mc/auth, а нужно тот, с котого зашли на сервер

### Любая дополнительная информация

:trollface:

**Comment by rsmanito** [comment]
```
rpc AddUserIP (AddUserIPRequest) returns (AddUserIPResponse);
 
message AddUserIPRequest{
  int64 id = 1;
  string ip = 2;
  string accessType = 3;
}

enum envType {
  OTHER = 0;
  RP = 1;
  CRP = 2;
  GCA = 3;
  WEB = 4;
}
```

RP/CRP/GCA will do

![IMG_0227](https://github.com/user-attachments/assets/188a6c82-8fe0-4d12-a399-8f1d0f8f7641)

**Comment by itsSourCream** [comment]
@rsmanito, чому `accessType` это строка
