### ISSUE TITLE
В нике нельзя поменять регистр символов

### ISSUE THREAD

**Issue by thehaffk** [digitaldrugstech/prdx-bugtracker#15]
В дискорде было бы неплохо иметь возможность сменить ник с apehum на Apehum и с faffelka на Faffelka, нынешняя пепега не дает так делать нах бля нах 
![image](https://github.com/user-attachments/assets/bbc4f3ef-8c5f-4de0-8b5d-d219d57ca924)

**Comment by itsSourCream** [comment]
![image](https://github.com/user-attachments/assets/68c0fa10-57fb-4abd-a40b-669c541cb9d1)
