### ISSUE TITLE
Невозможно отправить сообщение в чат

### ISSUE THREAD

**Issue by TheMek0** [digitaldrugstech/prdx-bugtracker#18]
### Опишите баг

Когда пишешь любое сообщение в чат, которое не является командой, то пишется ошибка, что сообщение небезопасно и его нельзя отправить

### Шаги для воспроизведения поведения

1. Зайдите на сервер "cr.prdx.so"
2. Пропишите команду `/server infrastructure`
3. Напишите любое сообщение в чат
4. Получите ошибку, что сервер не может отправить ваше сообщение

### Ожидаемое поведение

Поменять значение в каком-то конфиге, вооот...

### Если возможно, прикрепите скриншоты или видео

https://i.imgur.com/C2HEBWw.png

**Comment by thehaffk** [comment]
Чата нет в инфраструктуре, доступа к команде тоже не должно быть
