### ISSUE TITLE
Привести к одному языку описание тэгов на гитхабе

### ISSUE THREAD

**Issue by TheMek0** [digitaldrugstech/prdx-bugtracker#20]
### Четкое и сжатое описание проблемы

Сейчас каждое описание тэга написано либо на русском, либо на английском языке, а для дискорда вообще его нет

### Опишите решение, которое вы хотели бы получить

Хотелось бы видеть, чтобы описание для тэгов были приведены к одному языку, наверное лучше всего к английскому

### Дополнительный контекст

![image](https://github.com/user-attachments/assets/0ea064e8-072a-4f4b-b206-124708ae27bb)

**Comment by megazvezda** [comment]
Готово
