### ISSUE TITLE
не работают обьявления

### ISSUE THREAD

**Issue by Murchik0v** [digitaldrugstech/prdx-bugtracker#24]
### Опишите баг

не работают обьявления

### Шаги для воспроизведения поведения

1.Напишите в личные сообщения Боту обьявления

### Ожидаемое поведение

обьявления работают

### Если возможно, прикрепите скриншоты или видео

![image](https://github.com/user-attachments/assets/306125e1-9f3c-432f-8dcd-922742dbf3c3)

**Comment by thehaffk** [comment]
ты не игрок

**Comment by Murchik0v** [comment]
> ты не игрок

ну так дай игрока

**Comment by thehaffk** [comment]
не пиши мне

**Comment by Murchik0v** [comment]
> не пиши мне

Поздно
