### ISSUE TITLE
В спектаторе нельзя проходить сквозь блоки

### ISSUE THREAD

**Issue by itsSourCream** [digitaldrugstech/prdx-bugtracker#3]
**Опишите баг**
В режиме спектатора нельзя сквозь блоки проходить 😭 

**Для воспроизведения**
1. Перейти в режим спектатора
2. Попробовать пройти сквозь блоки

**Ожидаемое поведение**
В режиме спектатора можно сквозь блоки проходить 

**Дополнительная информация**
Работает при определенных условиях, виноват LimboAPI

**Comment by Komo4ekoI** [comment]
Мне можно

**Comment by thehaffk** [comment]
Невозможно возпроизвести, никто из хелперов/админов не сталкивается с таким, закрыто до того как кто-то из дев тимы с таким столкнется

**Comment by thehaffk** [comment]
![image](https://github.com/user-attachments/assets/df495fbe-83a1-4386-81ea-fe11eb54bd28)
Непонятно как воспроизвести, но иногда всё-таки срабатывает

**Comment by itsSourCream** [comment]
Появляется после телепортации через кастомные порталы?

**Comment by thehaffk** [comment]
> Появляется после телепортации через кастомные порталы?

это до порталов было + работает если переходить через /server

**Comment by thehaffk** [comment]
Пофикшено удалением LimboAPI, теперь нет бесшовных рестартов, но и баг больше не возникает
