### ISSUE TITLE
авторизация

### ISSUE THREAD

**Issue by Nilyfi** [digitaldrugstech/prdx-bugtracker#6]
### Опишите баг

не происходит автоматический кик после авторизации с лимбо, также не показывается сообщение об успешной авторизации (хз может так и надо)

### Шаги для воспроизведения поведения

1. Зайдите на сервер "prdx.so"
2. Нажмите "Нажмите для авторизации"
3. Пройдите авторизацию
4. Всё

### Ожидаемое поведение

Я ожидал, что у меня высветится сообщение в чате об успешной авторизации (опять же хз, может и не должно быть априори этого), а также сразу перенесёт на основной сервер из лимбо. Как итог я форсированно перезашёл (включил автокликер и поотправлял этим самым дофига пакетов) и меня перенесло в другой мир

### Minecraft (если ошибка связана с визуальными багами / сложностями при входе на сервер)

- Версия: [1.21 Fabric]
- Лаунчер [MultiMC Launcher]

**Comment by thehaffk** [comment]
"Как итог я форсированно перезашёл (включил автокликер и поотправлял этим самым дофига пакетов) и меня перенесло в другой мир" В какой мир? Ни на одном игроков сервере нет логов о входе
Когда ты это делал?

**Comment by itsSourCream** [comment]
Было пофикшено сегодня ночью, теперь игрока должно кикать с прокси
