### ISSUE TITLE
Нельзя поставить ник, если он начинается на цифру

### ISSUE THREAD

**Issue by thehaffk** [digitaldrugstech/prdx-bugtracker#7]
![image](https://github.com/user-attachments/assets/480eeaa5-ce82-46d1-a7d2-f432f26807d0)
![image](https://github.com/user-attachments/assets/8b09aa34-6ada-4c8a-9aec-de765f304672)
![image](https://github.com/user-attachments/assets/c4e9c897-b4b7-4c43-b2b9-68e3040d88c1)

**Comment by thehaffk** [comment]
https://github.com/digitaldrugstech/pepega-service/pull/11

**Comment by thehaffk** [comment]
а, вы не видите наверное
![image](https://github.com/user-attachments/assets/b976b0a4-7f36-4b27-be4d-f576f67e1159)

**Comment by Komo4ekoI** [comment]
НА ПРОД
