### ISSUE TITLE
проблема с GSit (возможно)

### ISSUE THREAD

**Issue by Nilyfi** [digitaldrugstech/prdx-bugtracker#9]
### Опишите баг

странное поведение при нажатии клавиши Shift два раза. некоторое время ещё остаётся тот блок барьера (возможно десинк), который ставился плагином

### Шаги для воспроизведения поведения

1. Зайдите на сервер "cr.prdx.so/prdx.so"
2. Нажмите SHIFT два раза
3. С надетыми элитрами прыгать, чтобы взлететь
4. Лететь фейерверками

### Ожидаемое поведение

Барьер должен убираться сразу после того, как игрок уйдёт из под него (это возможно десинк), да и наверное с элитрами такого происходить мне кажется вообще не должно

### Если возможно, прикрепите скриншоты или видео

лень

### Технические характеристики

- ОС: Windows / Mac / Linux
- Видеокарта, процессор
- Оперативная память

### Minecraft (если ошибка связана с визуальными багами / сложностями при входе на сервер)

- Версия: [1.21 Fabric]
- Лаунчер [MultiMC Launcher]

**Comment by thehaffk** [comment]
Не баг, /crawl держит тебя в состоянии лежания до тех пор, пока ты не нажмешь shift
